### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by ronilbhatia** [joshuachoi0508/OfficeGram#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* Please add links to your live site and wiki pages in the same style as Bluebird
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
* Be more explicit about which feature is CRUD and state so in one of the bullet points for that MVP (photos and comments could both be CRUD).
* Add time estimates for completion of each MVP
* Add bullet points for User Auth
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* table and column names should be lowercase
* For `likes` you should index the combination of `[:user_id, :photo_id]`, and enforce uniqueness so that a user can't like the same photo twice. Same goes for followers with `[:user_id, :follower_id]`
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* camelCase key names in sample state
* Michael Scott's bio cracked me up :)
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* `GET /users` - is this going to display information for just one user? If so, will this always be for the current user? I am just curious how you are going to use this route, and whether it makes more sense to have a `GET /users/:id` to render info for a specific user.
* What is your plan on rendering a photo feed for your users? Currently you have a `GET /photos` route which is your photos index. My question is will this be used to fetch every single photo on your app, or just all photos for a specific user? You might want to consider making a `GET /users/:id/photos` route to get all photos for a user's profile feed, and have this route be used simply to fetch all photos in your app for the general feed (or even better, only photos made by users who the current user follows). When we talk lets discuss your plan for how to handle these two separate feeds (general & profile).
* Check out the reading on superfluous routes linked above - none of your `likes`, `comments`, or `follows` routes need to be nested. Your React component should have access to the relevant foreign_key and be able to pass it up to the controller, such that your controller has access to that foreign_key in params without needing a nested route. We can discuss this more in person if not clear from the reading.
* snake_case your wildcards here since we're on the backend
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
* Please check out the format in Bluebird and redo this doc similarly. Right now I have no idea what your main components are and which routes will be rendering them. I also don't know what sub-components you're going to be using and where you'll be rendering them. Once you have fixed it I can revisit and offer my thoughts.
---

# Overall

I love the theme of the app and am really excited to see your final product with great seed data :). Please complete the frontend routes doc ASAP so I can complete my review and then make sure to set up the home page of your wiki appropriately.

**Comment by joshuachoi0508** [comment]
Hey Ronil, thanks for reviewing my wiki page. I made the needed revisions!
